name: base
channels:
  - defaults
dependencies:
  - pip
  - conda
  - pip:
    - chardet==3.0.4
    - pathlib==1.0.1
    - pyqt5==5.12.3
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.12.1
    - pyqtwebengine-qt5==5.15.2
    - requests==2.28.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - urllib3==1.26.12
    - gym
    - matplotlib
    - pybullet
    - stable-baselines3
    - h5py
